title: Paken for beginners
description: Paken Web 
author: Paken
logo: /beginners/static/img/avatar.png
github: https://github.com/TKPaken
about: for beginners

baseurl: "/"
url: "https://TKPaken.github.io"

allowsearch: true

disqus_shortname: paken

share:
  twitter_username: tk_paken


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
