site_name: Paken for beginners
site_url: https://tkpaken.github.io/beginners/
repo_url: https://github.com/TKPaken/beginners/
repo_name: TKPaken/beginners
site_author: 筑駒パ研
site_description: >-
  筑駒パ研の新入生用サイト
theme:
  name: material
  custom_dir: overrides
  language: ja
  favicon: assets/avatar.png
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TKPaken/beginners
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tk_paken

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Contact: contact.md
  - 競プロ:
    - 第0章 - パ研へようこそ！: programming/chapter0/index.md
    - 第1章 - プログラミングとは？: programming/chapter1/index.md
    - 第2章 - プログラミングを体感してみよう！: programming/chapter2/index.md
    - 第3章 - 本格的なプログラムを書いてみよう！:
      - 本格的なプログラムを書いてみよう！ (準備編): programming/chapter3/geany.md
      - 本格的なプログラムを書いてみよう！ (本編): programming/chapter3/apg4b.md
    - 第4章 - 実力アップに役立つサイト集＋実践演習: programming/chapter4/index.md
    - 第5章 - パ研での今後の活動: programming/chapter5/index.md
    - 第6章 - プログラミング環境を構築しよう！:
      - 環境構築まとめ: programming/chapter6/index.md
      - Windows(Visual Studio): programming/chapter6/windows-visualstudio.md
      - Windows(MinGW): programming/chapter6/windows-mingw.md
      - Mac(XCode): programming/chapter6/mac-xcode.md
      - Mac(GCC+VSCode): programming/chapter6/mac-gcc.md
      - Windows-VM: programming/chapter6/virtualbox-windows.md
      - Mac-VM: programming/chapter6/virtualbox-mac.md
      - Ubuntu-VM: programming/chapter6/ubuntu-virtualmachine.md
    - 第7章 - 目指せJOI本選！: programming/chapter7/index.md
  - CTF:
    - overview: CTF/index.md
  - OS:
    - overview: OS/index.md