site_name: Introduction to Paken
site_url: https://tkpaken.github.io/introduction/
repo_url: https://github.com/TKPaken/introduction/
repo_name: TKPaken/introduction
site_author: 筑駒パ研
site_description: >-
  筑駒パ研の新入生用サイト
theme:
  name: material
  custom_dir: overrides
  language: ja
  favicon: assets/avatar.png
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TKPaken/introduction
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tk_paken

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Contact: contact.md
  - 競プロ: 
    - 競技プログラミング班の紹介: CP/index.md
  - CTF:
    - CTF 班の紹介: CTF/index.md
  - 自作 OS:
    - overview: OS/index.md
  - Web:
    - overview: Web/index.md
  - アプリ:
    - overview: App/index.md
